### ISSUE TITLE
Add `ai_apps` to support Apps like Devin

### ISSUE THREAD

**Issue by suzuki-shunsuke** [suzuki-shunsuke/validate-pr-review-action#114]
### Feature Overview

This issue proposes to add an input like `ai_apps`.

### Why is the feature needed?

If you create a pull request by Devin but a pull request author is you, many people expect the pull request can be merged if a person is reviewed.
But actually validate-pr-review-action requires at least 2 approve because the committer of the commit of the pull request is Devin.

Malicious users can modify the commit history of the pull request using untrusted apps, so this restriction is reasonable, but this is inconvenient.

### Example Code

GitHub Actions

```yaml
- uses: suzuki-shunsuke/validate-pr-review-action@latest
  with:
    ai_apps: |
      devin-ai-integration
```
